### ISSUE TITLE
Error when entering API Key

### ISSUE THREAD

**Issue by mindmergedesign** [krve/statamic-google-maps#2]
I get an error message when I enter my API key on the settings page. I am running Statamic 2.6.0

**Comment by krve** [comment]
What error message do you get?

**Comment by mindmergedesign** [comment]
There was a problem saving your data. Please check your logs.

**Comment by krve** [comment]
Hmm.. I seem to have this problem with other addons as well after some testing. Not quite sure if it is an issue with statamic itself.

**Comment by mindmergedesign** [comment]
I am running Statamic 2.6.0. It seems that they new update has some breaking changes for some plugins.  https://statamic.com/changelog

Here is something that might help taken from the Changelog:
```
Break
Your extra addon classes should longer extend Addon. Instead, you should use the Extensible trait to get access to helper methods.
```

**Comment by krve** [comment]
Just saw that yeah. But it doesn't seem to concern this addon as the only class I have is the GoogleMapsTags which extends `Tags`. (I tried switching it).

EDIT: Also the Tags class has `use Extensible` at the top

**Comment by krve** [comment]
I tracked it down to AddonsController line 174. It seems the `$this->request` object is null. If i switch it out with the helper function `request('fields')` it works fine..

**Comment by krve** [comment]
This is a statamic issue: https://github.com/statamic/v2-hub/issues/1507

**Comment by mindmergedesign** [comment]
Thanks, I updated the AddonsController and it works now
