### ISSUE TITLE
Domain Verification and Using While Local

### ISSUE THREAD

**Issue by twd3** [krve/statamic-google-maps#3]
Could you maybe add to the docs the domain verification process Google will make you do for new API key? Also, How to handle the verification process when you are developing in a local environment and the verify via registrar isn't an option? ie: How would I verify somedomain.test.

**Comment by krve** [comment]
I think i'd rather add a link to their own guide or else I have to keep the guide updated.

This link should help you: https://developers.google.com/maps/documentation/javascript/get-api-key
